server:
  port: 8084

spring:
  main:
    web-application-type: none
  mongo:
    #uri: mongodb://mongodb_container:27017/alertbot_db?replicaSet=rs0
    uri: mongodb://mongodb_container:27017/alertbot_db
  kafka:
    bootstrap-servers: broker:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: nlp_results-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true
