name: CI/CD Maven â†’ Docker Hub
 
on:
  push:
    branches: [ "main" ]
    tags:     [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]
 
env:
  # Cambia si quieres publicarlo con otro nombre/namespace
  IMAGE_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  JAVA_VERSION: "21" 
 
jobs:
  build_test_package:
    name: Build + Test + Package (Maven)
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout #entrar al repositorio
        uses: actions/checkout@v4
 
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
 
      - name: Maven verify (build + test + package)
        run: |
          chmod +x ./mvnw || true
          ./mvnw clean package
 
      - name: Publicar artefacto .jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            **/target/*.jar
          if-no-files-found: error
 
  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: [ build_test_package ]
    permissions:
      contents: read
      packages: write
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Descargar .jar empaquetado
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/


      
      - name: Mostrar archivos en build
        run: ls -l build

 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Extraer metadatos (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
 
      - name: Construir y publicar imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            JAR_FILE=$(ls -1 build/*.jar | head -n1)
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Descomenta para multi-arch:
          # platforms: linux/amd64,linux/arm64
 
      - name: Mostrar tags publicados
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "${{ steps.meta.outputs.tags }}"
